# our main test script
services: docker
language: ruby
# only test 'push' builds to master (including PRs that target master)
branches:
  only:
    - master

# below are specific matrix includes for building documentation
#    and running cppcheck (not actually used)
matrix:
  fast_finish: true
  include:
    - language: cpp
      sudo: required
      services:
        - docker
      env: JOB="uncrustify check"
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull unibeautify/uncrustify
      script:
        - docker run -it -v "$(pwd)":/workdir -w /workdir unibeautify/uncrustify -c ci/uncrustify.cfg --check **/**.cxx || exit 0

    - language: python
      python: "3.7"
      env: JOB="Parsing xAODAnaHelpers/HelperClasses.h for InfoSwitches"
      dist: xenial
      sudo: true
      addons:
        apt:
          packages: libclang-6.0-dev
      before_script:
        - sudo ln -s /usr/lib/x86_64-linux-gnu/libclang-6.0.so /usr/lib/libclang.so
      install:
        - pip install clang
      script:
        - python3 ci/parse_infoswitches.py
        - git diff --no-prefix -- data/xAH_infoswitches.json
        - git diff --exit-code --name-only -- data/xAH_infoswitches.json

notifications:
  email:
    on_success: never
    on_failure: always
